name: destiny2_api
version: 0.1.0
description: Destiny2 API client
dependencies:
  http: '>=0.11.1 <0.12.0'
  dartson: "^0.2.4"

dev_dependencies:
  guinness: '^0.1.17'
  browser: any

transformers:
  - dartson
